// ── Types ─────────────────────────────────────────────────────────────────────
export type Video = {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  youtubeId: string;
  premium: boolean;
  category: string;
  duration: string;
  instructor: string;
  courseId?: string;
  order: number;
  views: number;
  publishedAt: string;
};

export type VideoCategory = { id: string; label: string };

// ── Categories ────────────────────────────────────────────────────────────────
export const VIDEO_CATEGORIES: VideoCategory[] = [
  { id: "all",              label: "All Videos" },
  { id: "new-testament",   label: "New Testament" },
  { id: "old-testament",   label: "Old Testament" },
  { id: "prayer",          label: "Prayer" },
  { id: "christian-living",label: "Christian Living" },
  { id: "worship",         label: "Worship" },
  { id: "ministry",        label: "Ministry" },
];

// ── Mock videos ───────────────────────────────────────────────────────────────
// Replace youtubeId values with real unlisted YouTube video IDs before going live.
export const MOCK_VIDEOS: Video[] = [
  {
    id: "v1",
    title: "Introduction to the Gospel of John",
    description: "Explore the opening chapter of John and discover the profound truth about the Word becoming flesh among us.",
    thumbnail: "https://images.unsplash.com/photo-1504052434569-70ad5836ab65?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: false,
    category: "new-testament",
    duration: "8:32",
    instructor: "Pastor David Mensah",
    courseId: "c1",
    order: 1,
    views: 1240,
    publishedAt: "Jun 1, 2026",
  },
  {
    id: "v2",
    title: "The Bread of Life — John 6",
    description: "Jesus declares 'I am the bread of life.' Understand what this means for our daily walk with God.",
    thumbnail: "https://images.unsplash.com/photo-1529070538774-1843cb3265df?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: true,
    category: "new-testament",
    duration: "18:22",
    instructor: "Pastor David Mensah",
    courseId: "c1",
    order: 2,
    views: 980,
    publishedAt: "Jun 5, 2026",
  },
  {
    id: "v3",
    title: "Walking on Water — Faith in the Storm",
    description: "A deep study of Peter's faith and fear, and what it means to keep our eyes fixed on Jesus.",
    thumbnail: "https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: true,
    category: "new-testament",
    duration: "13:55",
    instructor: "Pastor David Mensah",
    courseId: "c1",
    order: 3,
    views: 872,
    publishedAt: "Jun 9, 2026",
  },
  {
    id: "v4",
    title: "The Power of Prayer",
    description: "Learn how to develop a consistent, powerful prayer life deeply rooted in Scripture.",
    thumbnail: "https://images.unsplash.com/photo-1445112098124-3e76dd67983c?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: false,
    category: "prayer",
    duration: "9:15",
    instructor: "Pastor James Adeyemi",
    courseId: "c3",
    order: 1,
    views: 2100,
    publishedAt: "May 28, 2026",
  },
  {
    id: "v5",
    title: "Intercession — Standing in the Gap",
    description: "Understanding intercession as a spiritual discipline and its transformative impact on the Church.",
    thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: true,
    category: "prayer",
    duration: "14:40",
    instructor: "Pastor James Adeyemi",
    courseId: "c3",
    order: 2,
    views: 740,
    publishedAt: "Jun 2, 2026",
  },
  {
    id: "v6",
    title: "Grace and Salvation — What the Gospel Demands",
    description: "A foundational look at what it means to be saved by grace through faith alone in Christ.",
    thumbnail: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: false,
    category: "christian-living",
    duration: "11:28",
    instructor: "Pastor Sarah Okafor",
    courseId: "c2",
    order: 1,
    views: 1560,
    publishedAt: "May 20, 2026",
  },
  {
    id: "v7",
    title: "Living Holy in the Modern World",
    description: "Practical biblical guidance on holiness, discipline, and sanctification in everyday life.",
    thumbnail: "https://images.unsplash.com/photo-1499084732479-de2c02d45fcc?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: true,
    category: "christian-living",
    duration: "16:55",
    instructor: "Pastor Sarah Okafor",
    courseId: "c2",
    order: 2,
    views: 610,
    publishedAt: "May 25, 2026",
  },
  {
    id: "v8",
    title: "Worship in Spirit and Truth",
    description: "What does true worship look like? John 4 guides our understanding of God-centred worship.",
    thumbnail: "https://images.unsplash.com/photo-1492546643178-71bca3b6c408?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: false,
    category: "worship",
    duration: "10:10",
    instructor: "Pastor Ruth Eze",
    order: 1,
    views: 1890,
    publishedAt: "Jun 12, 2026",
  },
  {
    id: "v9",
    title: "Servant Leadership in Ministry",
    description: "Discover the biblical model of leadership: how to lead with humility, integrity, and grace.",
    thumbnail: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: true,
    category: "ministry",
    duration: "20:05",
    instructor: "Pastor Ruth Eze",
    courseId: "c4",
    order: 1,
    views: 450,
    publishedAt: "Jun 15, 2026",
  },
  {
    id: "v10",
    title: "Creation and the Character of God",
    description: "An overview of Genesis 1–2 and what creation reveals about the nature and purpose of God.",
    thumbnail: "https://images.unsplash.com/photo-1465101162946-4377e57745c3?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: true,
    category: "old-testament",
    duration: "17:30",
    instructor: "Pastor Daniel Yusuf",
    courseId: "c5",
    order: 1,
    views: 320,
    publishedAt: "Jun 18, 2026",
  },
  {
    id: "v11",
    title: "The Psalms — Songs of the Heart",
    description: "Walking through selected Psalms and discovering how they speak to every emotion and season of life.",
    thumbnail: "https://images.unsplash.com/photo-1464639351491-a172c2aa2911?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: false,
    category: "old-testament",
    duration: "12:44",
    instructor: "Pastor Daniel Yusuf",
    courseId: "c5",
    order: 2,
    views: 760,
    publishedAt: "Jun 20, 2026",
  },
  {
    id: "v12",
    title: "Defending the Faith — Apologetics Intro",
    description: "Learn how to gracefully and confidently give a reason for the hope that you have in Christ.",
    thumbnail: "https://images.unsplash.com/photo-1455849318743-b2233052fcff?w=640&q=80",
    youtubeId: "dQw4w9WgXcQ",
    premium: false,
    category: "christian-living",
    duration: "11:00",
    instructor: "Pastor Grace Amadi",
    courseId: "c6",
    order: 1,
    views: 930,
    publishedAt: "Jun 22, 2026",
  },
];
