[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions-internal/server"
  status = 200
  force = true
