[build]
  command = "npm run build"
  publish = ".output/public"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions-internal/server"
  status = 200
  force = true
