/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BibleAcademyRouteImport } from './routes/bible-academy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleAcademyRoute = BibleAcademyRouteImport.update({
  id: '/bible-academy',
  path: '/bible-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bible-academy': typeof BibleAcademyRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/ministries': typeof MinistriesRoute
  '/sermons': typeof SermonsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bible-academy': typeof BibleAcademyRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/ministries': typeof MinistriesRoute
  '/sermons': typeof SermonsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bible-academy': typeof BibleAcademyRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/ministries': typeof MinistriesRoute
  '/sermons': typeof SermonsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bible-academy'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/donations'
    | '/events'
    | '/login'
    | '/ministries'
    | '/sermons'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/bible-academy'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/donations'
    | '/events'
    | '/login'
    | '/ministries'
    | '/sermons'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bible-academy'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/donations'
    | '/events'
    | '/login'
    | '/ministries'
    | '/sermons'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BibleAcademyRoute: typeof BibleAcademyRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DonationsRoute: typeof DonationsRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MinistriesRoute: typeof MinistriesRoute
  SermonsRoute: typeof SermonsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible-academy': {
      id: '/bible-academy'
      path: '/bible-academy'
      fullPath: '/bible-academy'
      preLoaderRoute: typeof BibleAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BibleAcademyRoute: BibleAcademyRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DonationsRoute: DonationsRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MinistriesRoute: MinistriesRoute,
  SermonsRoute: SermonsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

